server:
  port: 9527


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://www.eureka7001.com:7001/eureka
  instance:
    instance-id: gateway9527
    prefer-ip-address: true


spring:
  application:
    name: gateway-main

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_fast #路由id，要求唯一
          # uri: http://localhost:8001 # 匹配后提供服务的路由地址
          uri: lb://TCLOUD-PAYMENT-PROVIDER # 匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/** # 断言，路径匹配的进行路由

        - id: payment_slow #路由id，要求唯一
          #uri: http://localhost:8001 # 匹配后提供服务的路由地址
          uri: lb://TCLOUD-PAYMENT-PROVIDER # 匹配后提供服务的路由地址
          predicates:
            - Path=/payment/out/** # 断言，路径匹配的进行路由
            #- Cookie=username,zzyy
            #- Query=username,zzyy
            #- Method=GET